"""empty message

Revision ID: 20d38d1a77b4
Revises: None
Create Date: 2018-05-28 13:15:49.271430

"""

# revision identifiers, used by Alembic.
revision = '20d38d1a77b4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortcuts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=True),
    sa.Column('url_template', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shortcuts')
    # ### end Alembic commands ###
